language: rust
rust:
  - stable
  - beta
  # Minimum supported Rust version (msrv)
  - 1.32.0
script: |
  cargo build --verbose &&
  cargo test  --verbose --all
matrix: # additional tests
  include:
  - rust: nightly
    script: cargo test --all --features nightly
  - rust: 1.29.1
    env: CLIPPY=YESPLEASE
    before_script: rustup component add clippy-preview
    script: cargo clippy --all -- -D warnings
  - rust: 1.29.1
    env: RUSTFMT=YESPLEASE
    before_script: rustup component add rustfmt-preview
    script: cargo fmt --all -- --check
cache: cargo
